# The default ResourceSync simulator configuration

##### Source Configuration #####

source:
    name: ResourceSync Simulator
    number_of_resources: 1000
    change_delay: 2
    event_types: [create, update, delete]
    average_payload: 1000
    max_events: -1

##### Inventory Configuration #####

# The Source exposes a dynamic inventory
# inventory:
#     class: DynamicSourceInventory
#     uri_path: sitemap.xml

# The Source exposes a static inventory
inventory:
    class: StaticSourceInventory
    max_sitemap_entries: 500
    interval: 15
    uri_path: sitemap.xml

##### ChangeMemory Configuration #####

# Change memory implementation used in the simulation
changememory:
    class: DynamicChangeSet
    uri_path: changes

##### Publisher Configuration #####

# publisher:
#     class: XMPPPublisher
#     jid: publisher_jid
#     pwd: pwd
#     pubsub_node: node_name
#     pubsub_jid: pubsub.host

# Event logger settings
logger:
    class: ConsoleEventLog
